Add Chinese-Simplified translation
olgamiller/SSTVEncoder2 pull request #15
Opened 2023-12-10 07:58 UTC by WeiguangTWK

DE BG7QWH and thank you for your awsome SSTV app

2023-12-10 09:26 UTC, olgamiller requested changes
Thank you for providing the translations.
Please see my comments.

2023-12-10 09:26 UTC, olgamiller commented on app/src/main/res/values-zh-rCN/strings.xml
> +    <string name="message_no_camera">这个设备没有摄像头╮(╯-╰)╭</string>
Please remove the smiley "╮(╯-╰)╭"

2023-12-10 09:26 UTC, olgamiller commented on app/src/main/res/values-zh-rCN/strings.xml
> +    <string name="outline">下划线</string>
"下划线" translates "underline" instead of "outline"

2023-12-10 09:26 UTC, olgamiller commented on app/src/main/res/values-zh-rCN/strings.xml
> +    <string name="outline_color">下划线颜色</string>
Same as "outline" above

2023-12-10 09:26 UTC, olgamiller commented on app/src/main/res/values-zh-rCN/strings.xml
> +    <string name="app_name">SSTV编码器</string>
"SSTV Encoder" app name shall not be translated

2023-12-10 09:26 UTC, olgamiller commented on app/src/main/res/values-zh-rCN/strings.xml
> +    <string name="action_about">关于SSTV编码器</string>
"SSTV Encoder" app name shall not be translated

2023-12-10 09:26 UTC, olgamiller commented on app/src/main/res/values-zh-rCN/strings.xml
> +    <string name="action_privacy_policy_text">\n        SSTV编码器可以将图片转换为音频\n        \n\n为实现转换功能，图像会被暂时载入内存.\n        \n\n图像可以被缩放或者选择. 别担心，此软件内对于图像的更改不会被保存. 最后一次使用的图片的路径会保存在软件的本地存储.\n        \n\n此外你还可以
- Please remove "别担心" ("Don't worry")
- "SSTV Encoder" app name shall not be translated

2023-12-10 10:14 UTC, WeiguangTWK commented
Okay and I will do some changes according to your comments :)

2023-12-10 10:30 UTC, WeiguangTWK commented
Change submitted, please see if there's another problem

2023-12-15 16:23 UTC, olgamiller commented
Thank you for the update.
Just one more thing: 
translatable="false" for "app_name" is missing

2023-12-16 12:46 UTC, WeiguangTWK commented
@olgamiller  OK, see if there's another thing to do :)

2023-12-17 13:54 UTC, olgamiller commented
Thank you.

Unfortunately, I've noticed a few issues (that existed before the changes, but are now “visible” with the changes):
- The "size" string will be used for both, Font and Outline (and therefore "字体大小" will also be used for Outline Size)
- The "color" string will be used instead of "outline_color" for the Outline Color
- The following values are not in the strings.xml (and therefore will not be translated):
  - EditTextActivity:
    - {"Small", "Normal", "Large", "Huge"}
    - {"Thin", "Normal", "Thick"}
  - FontFamilySet: "Default"

Would you like to fix these issues as well, all of them or a few? Otherwise, I'll merge this PR as it is now and fix the issues afterwards. Please let me know what you would prefer.

Additionally, I could not test the Font selection with System Language 简体中文. My emulator gets the "Default" item only, in the Font selection list. Would it be possible for you to check if it works as expected?

2023-12-17 23:00 UTC, WeiguangTWK commented
> Thank you.
> 
> Unfortunately, I've noticed a few issues (that existed before the changes, but are now “visible” with the changes):
> 
>     * The "size" string will be used for both, Font and Outline (and therefore "字体大小" will also be used for Outline Size)
> 
>     * The "color" string will be used instead of "outline_color" for the Outline Color
> 
>     * The following values are not in the strings.xml (and therefore will not be translated):
>       
>       * EditTextActivity:
>         
>         * {"Small", "Normal", "Large", "Huge"}
>         * {"Thin", "Normal", "Thick"}
>       * FontFamilySet: "Default"
> 
> 
> Would you like to fix these issues as well, all of them or a few? Otherwise, I'll merge this PR as it is now and fix the issues afterwards. Please let me know what you would prefer.
> 
> Additionally, I could not test the Font selection with System Language 简体中文. My emulator gets the "Default" item only, in the Font selection list. Would it be possible for you to check if it works as expected?


Oh I got what happend: string "size" and "colour" have been used twice and I failed to notice it😂, I will now update the translation and test it, screenshot and new commit will be done soon

2023-12-17 23:25 UTC, WeiguangTWK commented
@olgamiller My IDE notices me that 10 warnings generated about activity_edit_text.xml, maybe some fixes are needed but at least now that two strings work on my phone

![屏幕截图 2023-12-18 072005](https://github.com/olgamiller/SSTVEncoder2/assets/41853928/ffdf82a5-bf9d-44cc-b034-05d7c46e77a0)
![1702855343702](https://github.com/olgamiller/SSTVEncoder2/assets/41853928/0c0e8c4a-1465-44e3-aac9-2040fab3f8a6)
![1702855343689](https://github.com/olgamiller/SSTVEncoder2/assets/41853928/3f345f3f-327e-4aa5-b854-d8690f504c2d)
![1702855343684](https://github.com/olgamiller/SSTVEncoder2/assets/41853928/207d46d6-a0c7-4a27-bdc9-405e35cb6a01)
![1702855343680](https://github.com/olgamiller/SSTVEncoder2/assets/41853928/d70d7a9e-52cd-48c9-99bb-947478324f57)

Check if there's any issues and I will try my best to assist

2023-12-18 09:25 UTC, merged

2023-12-18 09:44 UTC, olgamiller commented
Yeah, this project is old, Android has changed a lot, therefore the warnings everywhere.
Your changes are merged. Thanks for the fixes, and for the translations.

One question: Would the following translation make sense?
- "Small" -> “小的”
- "Normal" -> “普通的”
- "Large" -> “大的”
- "Huge" -> “巨大的”
- "Thin" -> “薄的”
- "Normal" -> “普通的”
- "Thick" -> “厚的”
- "Default" -> “默认”

2023-12-18 11:45 UTC, olgamiller commented
I've added missing strings to the string resources (see the latest updates). May I ask you to check whether the translation makes sense:
```
    ...
    <string name="progressbar_message_sending">发送…</string>
    <string name="progressbar_message_saving_to_file">%1$s 保存…</string>
    ...
    <string name="font_default">默认</string>
    ...
    <string name="font_size_small">小的</string>
    <string name="font_size_normal">普通的</string>
    <string name="font_size_large">大的</string>
    <string name="font_size_huge">巨大的</string>
    ...
    <string name="outline_size_thin">薄的</string>
    <string name="outline_size_normal">普通的</string>
    <string name="outline_size_thick">厚的</string>
```
(Please feel free to update/fix via another PR if necessary. Thanks.)

2023-12-18 13:02 UTC, WeiguangTWK commented
> Yeah, this project is old, Android has changed a lot, therefore the warnings everywhere. Your changes are merged. Thanks for the fixes, and for the translations.
> 
> One question: Would the following translation make sense?
> 
>     * "Small" -> “小的”
> 
>     * "Normal" -> “普通的”
> 
>     * "Large" -> “大的”
> 
>     * "Huge" -> “巨大的”
> 
>     * "Thin" -> “薄的”
> 
>     * "Normal" -> “普通的”
> 
>     * "Thick" -> “厚的”
> 
>     * "Default" -> “默认”

Generally speaking, that translation makes sense. But in many cases it depends on which kind of objects you're describing. For example, about the description of text or font, if you translate "huge" into "巨大的"—— although it might still make sense, but some how makes people feel strange to see expression like that and we call it "translation tone（翻译腔）" so in this example I prefer to translate "huge" into "特大号" like "XXL" size of clothes

2024-01-07 10:45 UTC, olgamiller commented
@WeiguangTWK: Could you please provide an improved translation of the following strings (so the Chinese-Simplified translation would be really complete):
```...
    <string name="progressbar_message_sending">发送…</string>
    <string name="progressbar_message_saving_to_file">%1$s 保存…</string>
    ...
    <string name="font_default">默认</string>
    ...
    <string name="font_size_small">小的</string>
    <string name="font_size_normal">普通的</string>
    <string name="font_size_large">大的</string>
    <string name="font_size_huge">巨大的</string>
    ...
    <string name="outline_size_thin">薄的</string>
    <string name="outline_size_normal">普通的</string>
    <string name="outline_size_thick">厚的</string>
```

2024-01-07 12:15 UTC, WeiguangTWK commented
@olgamiller Ok, here we go

`    <string name="progressbar_message_sending">发送…</string>
    <string name="progressbar_message_saving_to_file">%1$s 另存为文件</string>
    ...
    <string name="font_default">默认字体</string>
    ...
    <string name="font_size_small">小</string>
    <string name="font_size_normal">常规</string>
    <string name="font_size_large">大</string>
    <string name="font_size_huge">很大</string>
    ...
    <string name="outline_size_thin">细</string>
    <string name="outline_size_normal">常规</string>
    <string name="outline_size_thick">粗</string>`

2024-01-07 12:15 UTC, WeiguangTWK commented
@olgamiller Ok, here we go
‘
    <string name="progressbar_message_sending">发送…</string>
    <string name="progressbar_message_saving_to_file">%1$s 保存…</string>
    ...
    <string name="font_default">默认</string>
    ...
    <string name="font_size_small">小的</string>
    <string name="font_size_normal">普通的</string>
    <string name="font_size_large">大的</string>
    <string name="font_size_huge">巨大的</string>
    ...
    <string name="outline_size_thin">薄的</string>
    <string name="outline_size_normal">普通的</string>
    <string name="outline_size_thick">厚的</string>
’

2024-01-07 12:17 UTC, WeiguangTWK commented
@olgamiller Ok, here we go
(Since some problem occured I deleted and reedit my reply, never mind)

`
    <string name="progressbar_message_sending">发送…</string>
    <string name="progressbar_message_saving_to_file">%1$s 另存为文件</string>
    ...
    <string name="font_default">默认字体</string>
    ...
    <string name="font_size_small">小</string>
    <string name="font_size_normal">常规</string>
    <string name="font_size_large">大</string>
    <string name="font_size_huge">很大</string>
    ...
    <string name="outline_size_thin">细</string>
    <string name="outline_size_normal">常规</string>
    <string name="outline_size_thick">粗</string>
`

2024-01-07 15:53 UTC, olgamiller commented
@WeiguangTWK: Thank you, I've implemented your suggestions.